admin_site_rubriques_list:
  path: /rubriques
  defaults: {_controller: AppBundle\Controller\Admin\Site\ListRubriquesAction}

admin_site_rubriques_add:
  path: /rubriques/add
  defaults: {_controller: AppBundle\Controller\Admin\Site\AddRubriqueAction}
  
admin_site_rubriques_edit:
  path: /rubriques/edit/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Site\EditRubriqueAction}
  requirements:
    id: '\d+'

admin_site_rubriques_delete:
  path: /rubriques/delete/{id}/{token}
  defaults: {_controller: AppBundle\Controller\Admin\Site\DeleteRubriqueAction}
  requirements:
    id: '\d+'
    token: '[a-zA-Z0-9_-]+'

admin_site_feuilles_list:
  path: /feuilles
  defaults: {_controller: AppBundle\Controller\Admin\Site\ListFeuillesAction}

admin_site_feuilles_add:
  path: /feuilles/add
  defaults: {_controller: AppBundle\Controller\Admin\Site\AddFeuilleAction}
  
admin_site_feuilles_edit:
  path: /feuilles/edit/{id}
  defaults: {_controller: AppBundle\Controller\Admin\Site\EditFeuilleAction}
  requirements:
    id: '\d+'

admin_site_feuilles_delete:
  path: /feuilles/delete/{id}/{token}
  defaults: {_controller: AppBundle\Controller\Admin\Site\DeleteFeuilleAction}
  requirements:
    id: '\d+'
    token: '[a-zA-Z0-9_-]+'


  
